export const iphones = [
  {
    model: "iPhone 13",
    price: 799,
    inStock: true,
    colors: ["black", "white", "blue"],
    releaseYear: 2021,
    rating: 4.8,
    discount: null,
    counter: 1,
    img:"https://w7.pngwing.com/pngs/736/372/png-transparent-iphone-12-back-thumbnail.png",
  },

  {
    model: "iPhone 14 Max",
    price: 999,
    inStock: true,
    colors: ["purple", "red", "yellow"],
    releaseYear: 2022,
    rating: 4.9,
    discount: 50,
    counter: 1,
    img:"https://assets.swappie.com/cdn-cgi/image/width=600,height=600,fit=contain,format=auto/swappie-iphone-14-pro-max-deep-purple-back.png?v=39c672df",
  },
  {
    model: "iPhone 12",
    price: 699,
    inStock: false,
    colors: ["green", "black", "white"],
    releaseYear: 2020,
    rating: 4.6,
    discount: 100,
    counter: 1,
    img:"https://cdn.alloallo.media/catalog/product/apple/iphone/iphone-12-pro-max/iphone-12-pro-max-gold-back.jpg"
  },
  {
    model: "iPhone SE (2022)",
    price: 429,
    inStock: true,
    colors: ["black", "white", "red"],
    releaseYear: 2022,
    rating: 4.5,
    discount: null,
    counter: 1,
    img:"https://cdn.idealo.com/folder/Product/201860/1/201860120/s1_produktbild_gross_8/apple-iphone-se-2022.jpg",
  },
  {
    model: "iPhone 13 Pro",
    price: 999,
    inStock: true,
    colors: ["blue", "silver", "gold"],
    releaseYear: 2021,
    rating: 4.8,
    discount: 70,
    counter: 1,
    img:"https://www.dimprice.de/image/cache/catalog/Apple/iphone-13-pro-blue-select-7-550x550.png",
  },
  {
    model: "iPhone 14 Pro",
    price: 1199,
    inStock: false,
    colors: ["purple", "gold", "black"],
    releaseYear: 2022,
    rating: 4.9,
    discount: 100,
    counter: 1,
   img:"https://m.media-amazon.com/images/I/61lKQWyMdDL.jpg",
  },
  {
    model: "iPhone 11",
    price: 599,
    inStock: true,
    colors: ["white", "black", "yellow"],
    releaseYear: 2019,
    rating: 4.4,
    discount: 50,
    counter: 1,
    img:"https://m.media-amazon.com/images/I/715aZpyanZL.jpg",
  },
  {
    model: "iPhone XR",
    price: 499,
    inStock: false,
    colors: ["coral", "blue", "black"],
    releaseYear: 2018,
    rating: 4.3,
    discount: 30,
    counter: 1,
    img:"https://m.media-amazon.com/images/I/715aZpyanZL.jpg"
  },
  {
    model: "iPhone 15",
    price: 1099,
    inStock: true,
    colors: ["black", "white", "pink"],
    releaseYear: 2023,
    rating: 5.0,
    discount: 100,
    counter: 1,
        img:"https://m.media-amazon.com/images/I/71vKy5OHuPL.jpg"
  },
  {
    model: "iPhone 15 Pro Max",
    price: 1499,
    inStock: true,
    colors: ["blue", "titanium", "black"],
    releaseYear: 2023,
    rating: 4.9,
    discount: 200,
    counter: 1,
        img:"https://m.media-amazon.com/images/I/81izs2I2UvL._AC_UF1000,1000_QL80_.jpg"
  },
];
